kind: pipeline
name: default

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -mod=vendor ./...
- name: lint
  image: golang:1.12
  commands:
  - go version
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - golangci-lint run ./...
