kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test -mod=vendor ./...

trigger:
  branch:
    - master
    - certbdd
  event:
    - pull_request
    - push