workspace:
base: /go
path: src/repo/goweb-app

pipeline:
  test:
    image: golang:1.12
    commands:
      - go test -mod=vendor ./...
  build:
    image: golang:1.12
    commands:
      - go build

#kind: pipeline
#name: default
#
#steps:
#- name: test
#  image: golang:1.12
#  commands:
#  - go test -mod=vendor ./...
#
#trigger:
#  branch:
#    - certbdd
#  event:
#    - push