build:
  image: golang:1.12.5
  commands:
    - go test -mod=vendor ./...

#kind: pipeline
#name: default
#
#steps:
#- name: UT
#  image: golang:1.12
#  commands:
#  - go test -mod=vendor ./...