worksapce:
  base: /go
  path: src/github.com/palletone

pipeline:
  build:
    image: golang:1.12.7
    environment:
      - BASE_DIR=/go/src/github.com/palletone/go-palletone
      - ALL_LOG_PATH=/go/src/github.com/palletone/go-palletone/bdd/node/log/all.log
      - GAS_TOKEN_ALL_LOG_PATH=/go/src/github.com/palletone/go-palletone/bdd/GasToken/node/log/all.log
      - BDD_LOG_PATH=/go/src/github.com/palletone/go-palletone/bdd/logs
      - CREATE_TRANS_DIR=createTrans
      - CONTRACT20_DIR=crt20Contract
      - SEQENCE721_DIR=crt721Seqence
      - UDID721_DIR=crt721UDID
      - VOTECONTRACT_DIR=voteContract
      - MULTIPLE_DIR=zMulti-node
      - DIGITAL_IDENTITY_DIR=Digital-IdentityCert
      - DEPOSIT_DIR=deposit
      - GAS_TOKEN_DIR=gasToken
      - MEDIATOR_VOTE_DIR=meidatorvote
      - USER_CONTRACT_DIR=usercontract
      - LOG_NAME=log.html
      - REPORT_NAME=report.html
      ##########  control testcase  ##############
      - IS_RUN_DEPOSIT=true
      - IS_RUN_TESTCONTRACTCASES=true
      - IS_RUN_CREATE_TRANS=true
      - IS_RUN_20CONTRACT=true
      - IS_RUN_721SEQENCE=true
      - IS_RUN_721UDID=true
      - IS_RUN_MULTIPLE=true
      - IS_RUN_DIGITAL=true
      - IS_RUN_VOTE=true
      - IS_RUN_GASTOKEN=true
      - IS_RUN_MEDIATOR_VOTE=true
      - GO111MODULE=on
      - IS_UPLOAD=true
    commands:
      - cd $GOPATH/src/github.com/palletone
      - git clone https://github.com/palletone/digital-identity.git
      - cd $BASE_DIR/bdd/Digital-Identity/scripts
      - chmod +x ca-start.sh
      - chmod +x one-ptn.sh
      - ./ca-start.sh
      - tree ~/cawork
      - ./one-ptn.sh
      - sleep 30
      - netstat -ntl
      - cd $BASE_DIR
      - mkdir -p ${BDD_LOG_PATH}/${DIGITAL_IDENTITY_DIR}
      - python -m robot.run -d ${BDD_LOG_PATH}/${DIGITAL_IDENTITY_DIR} ./bdd/Digital-Identity/testcases;