version: '2'

services:
  mediator1:
    container_name: mediator1
    image: palletone/mediator
    networks:
      gptn-net:
        ipv4_address: 172.11.0.2
    volumes:
     - ./scripts/node1/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
     - ./scripts/node1/ptn-config.toml:/palletone/mediator/ptn-config.toml
     - ./scripts/node1/palletone:/palletone/mediator/palletone
    restart: always
    command: ./gptn --noProduce --staleProduce
#    expose:
#      - "12345"
  mediator2:
    container_name: mediator2
    image: palletone/mediator
    volumes:
     - ./scripts/node2/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
     - ./scripts/node2/ptn-config.toml:/palletone/mediator/ptn-config.toml
     - ./scripts/node2/palletone:/palletone/mediator/palletone
    restart: always
    networks:
      gptn-net:
        ipv4_address: 172.11.0.3
#    expose:
#      - "12347"
  mediator3:
    container_name: mediator3
    image: palletone/mediator
    volumes:
     - ./scripts/node3/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
     - ./scripts/node3/ptn-config.toml:/palletone/mediator/ptn-config.toml
     - ./scripts/node3/palletone:/palletone/mediator/palletone
    restart: always
    networks:
      gptn-net:
        ipv4_address: 172.11.0.4
#    expose:
#      - "12348"
  mediator4:
    container_name: mediator4
    image: palletone/mediator
    volumes:
     - ./scripts/node4/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
     - ./scripts/node4/ptn-config.toml:/palletone/mediator/ptn-config.toml
     - ./scripts/node4/palletone:/palletone/mediator/palletone
    restart: always
    networks:
      gptn-net:
        ipv4_address: 172.11.0.5
#    expose:
#      - "12349"
  mediator5:
    container_name: mediator5
    image: palletone/mediator
    volumes:
     - ./scripts/node5/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
     - ./scripts/node5/ptn-config.toml:/palletone/mediator/ptn-config.toml
     - ./scripts/node5/palletone:/palletone/mediator/palletone
    restart: always
    networks:
      gptn-net:
        ipv4_address: 172.11.0.6
#    expose:
#      - "12350"
  node:
    container_name: node
    image: palletone/mediator
    volumes:
      - ./scripts/node6/ptn-genesis.json:/palletone/mediator/ptn-genesis.json
      - ./scripts/node6/ptn-config.toml:/palletone/mediator/ptn-config.toml
      - ./scripts/node6/palletone:/palletone/mediator/palletone
    restart: always
    networks:
      gptn-net:
        ipv4_address: 172.11.0.7

networks:
  gptn-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
          gateway: 172.11.0.1
